add asset header font size options
UNDP-Data/geohub pull request #1059
Opened 2022-12-30 18:13 UTC by Thuhaa

Asset header is now different from the main dataset accordion title
![image](https://user-images.githubusercontent.com/45137948/210100517-d229dc3a-2c80-40c1-8740-d2b1f48079da.png)

2023-01-01 11:17 UTC, JinIgarashi requested changes
Looks fine. Please fix a thing I commented regarding to storybook setting before merging.

2023-01-01 11:17 UTC, JinIgarashi commented on packages/svelte-undp-design/src/lib/Accordion/Accordion.stories.ts
>  	parameters: {
Could you add fontSize at parameters?

2023-01-03 11:11 UTC, Thuhaa commented
> @Thuhaa Looks fine. Please fix a thing I commented regarding to storybook setting before merging.

done

2023-01-03 12:49 UTC, JinIgarashi approved these changes

2023-01-03 12:55 UTC, merged