improve state management for vector layers
UNDP-Data/geohub pull request #1167
Opened 2023-01-16 16:04 UTC by Thuhaa

2023-01-16 16:37 UTC, Thuhaa commented
Fixes #1122 
Fixes #1130

2023-01-16 16:45 UTC, Thuhaa commented
**State management for the different vector layer components is improved**
1. `PropertySelect.svelte` component in the `VectorLegendAdvanced` ![image](https://user-images.githubusercontent.com/45137948/212728635-9c678af3-2c35-4b95-a8d1-094ee86e7d64.png)

  2. `numberOfClasses, and classificationMethod` and therefore the `colorMapRows` state is maintained 
![image](https://user-images.githubusercontent.com/45137948/212729083-d5fb54ce-d9a2-4656-be3b-7b18d1a322a8.png)

2023-01-16 17:13 UTC, JinIgarashi requested changes
@Thuhaa Don't add unnecessary props which can be extracted from maplibre layer style object.

2023-01-16 17:13 UTC, JinIgarashi commented on sites/geohub/src/components/VectorLayer.svelte
> +  let colorMapRows: Array<IntervalLegendColorMapRow> = []
we don't need to keep `numberOfClasses` and `colorMapRows` in this level.

2023-01-16 17:13 UTC, JinIgarashi commented on sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
> +  export let defaultOutlineColor: string
these four properties may not need to be exported. and all  information can be extracted from layer style object

2023-01-17 15:08 UTC, JinIgarashi requested changes
The colormap picker looks different from before??

<img width="825" alt="image" src="https://user-images.githubusercontent.com/2639701/212933784-ff9684f3-bf7f-4bb6-8762-b5f5d54b212e.png">

2023-01-17 15:08 UTC, JinIgarashi commented on sites/geohub/src/components/controls/VectorLegendPanel.svelte
> +          bind:propertySelectValue
delete this. this property is not exported

2023-01-17 17:51 UTC, JinIgarashi approved these changes

2023-01-17 17:51 UTC, merged